# Site settings
author: Nick Solony
title: Learn_to_code
header-img: img/home-bg.png
email: nicksolony@gmail.com
copyright_name: Nick Solony
description: > # this means to ignore newlines until "baseurl:"
  How did I learn to code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nicksolony

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
